config/routes.rb
Rails.application.routes.draw do
	devise_for :users

	devise_for :admins, controllers: {
		sessions: "admins/sessions",
		passwords: "admins/passwords"
	}

	root to: "homes#top"
	get "home/about", to: "homes#about"
	get "search", to: "homes#search"

	resources :users, except:[:new, :create]

	resources :posts, except:[:edit, :update] do
		resources :post_comments, only:[:create, :destroy]
		resources :likes, only:[:create, :destroy]
	end

	resources :notifications, only:[:index]
	delete "notifications/destroy", to: "notifications#destroy_all"

    namespace :admins do
		get "top", to: "users#top"

    	resources :users, only:[:index, :edit, :update]

    	resources :tags
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :validatable

	mount_uploader :profile_image, ProfileImageUploader

	has_many :posts, dependent: :destroy
	has_many :post_comments, dependent: :destroy
	has_many :likes, dependent: :destroy
	has_many :active_notifications, class_name: "Notification",
				foreign_key: "visiter_id", dependent: :destroy
	has_many :passive_notifications, class_name: "Notification",
				foreign_key: "visited_id", dependent: :destroy

	enum is_active: {Available: true, Invalid: false}

	with_options presence: true do
	  validates :email
	  validates :nickname, length: { in: 1..20 }
	end

	def active_for_authentication?
		super && (self.is_active === "Available")
	end

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
	before_action :authenticate_admin!
	before_action :get_user, only:[:edit, :update]

	def top
	end

	def index
		@users = User.all
	end

	def edit
	end

	def update
		if @user.update(admin_user_params)
			redirect_to admins_users_path
		else
			render ("admins/users/edit")
		end
	end

	protected

	def get_user
		@user = User.find(params[:id])
	end

	def admin_user_params
		params.require(:user).permit(
			:nickname,
			:profile_image,
			:email,
			:is_active
		)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :get_user, only:[:show, :edit, :update, :destroy]

	def show
		@posts = Post.where(user_id: @user.id).reverse_order.page(params[:page])
	end

	def index
		@users = User.where(is_active: true).page(params[:page]).per(12)
	end

	def edit
	end

	def update
		if	@user.update(user_params)
			redirect_to user_path(current_user)
		else
			render ("users/edit")
		end
	end

	def destroy
		@user.destroy
		redirect_to root_path
	end

	private

	def get_user
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(
			:nickname,
			:profile_image,
			:email,
			:is_active
		)
	end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/users/edit.html.erb
<div class="container">
	<div class="admin-user-list">
		<h1><%= @user.nickname %></h1>

		<%= form_for @user, url: admins_user_path, method: :patch do |f| %>

			<%= f.radio_button :is_active, "Available" %>有効
			<%= f.radio_button :is_active, "Invalid" %> 退会済み

			<%= f.submit "変更を保存する", class:"btn btn-success" %>
		<% end %>
	</div>
</div>

app/views/admins/users/index.html.erb
<div class="admin-user-list">
	<h2>ユーザ一覧</h2>
	<table class="table table-dark">
		<% @users.each do |user| %>
			<tr>
				<td><% if user.profile_image? %>
						<%= image_tag user.profile_image.url, class:"user_profile_image_post_index" %>
					<% else %>
						<div class="user-no-profile">
							<i class="fas fa-user-circle fa-5x"></i>
						</div>
					<% end %>
				</td>
				<td><%= user.nickname %></td>
				<td>投稿：<%= user.posts.count %>件</td>
				<td><% if user.is_active == "Available" %>
						有効
					<% else %>
						無効
					<% end %>
				</td>
				<td><%= link_to "編集", edit_admins_user_path(user.id), class:"btn btn-success"%></td>
			</tr>
		<% end %>
	</table>

</div>

app/views/admins/users/top.html.erb
<div class="container">
	<div class="admin-user-list">
		<h1>Admin top</h1>

		<span><%= link_to "ユーザ管理", admins_users_path, class:"btn btn-primary" %></span>

		<span><%= link_to "タグ管理", admins_tags_path, class:"btn btn-warning" %></span>

		<span><%= link_to "LogOut", destroy_admin_session_path, method: :delete, class:"btn btn-danger" %></span>
		<p class="admin-top-text">footerの文字からAdmin topに戻れます</p>
	</div>
</div>