config/routes.rb
Rails.application.routes.draw do
	devise_for :users

	devise_for :admins, controllers: {
		sessions: "admins/sessions",
		passwords: "admins/passwords"
	}

	root to: "homes#top"
	get "home/about", to: "homes#about"
	get "search", to: "homes#search"

	resources :users, except:[:new, :create]

	resources :posts, except:[:edit, :update] do
		resources :post_comments, only:[:create, :destroy]
		resources :likes, only:[:create, :destroy]
	end

	resources :notifications, only:[:index]
	delete "notifications/destroy", to: "notifications#destroy_all"

    namespace :admins do
		get "top", to: "users#top"

    	resources :users, only:[:index, :edit, :update]

    	resources :tags
    end
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :posts

	validates :tag_name, presence: true

end

app/controllers/admins/tags_controller.rb
class Admins::TagsController < ApplicationController
	before_action :authenticate_admin!
	before_action :get_tag, only:[:edit, :update, :destroy]

	def index
		@tag = Tag.new
		@tags = Tag.all
	end

	def create
		@tag = Tag.new(tag_params)
		@tag.save
		redirect_to admins_tags_path
	end

	def edit
	end

	def update
		if @tag.update(tag_params)
			redirect_to admins_tags_path
		else
			render 'edit'
		end
	end

	def destroy
		@tag.destroy
		redirect_to admins_tags_path
	end

	private

	def get_tag
		@tag = Tag.find(params[:id])
	end

	def tag_params
		params.require(:tag).permit(:tag_name)
	end
end

app/helpers/admins/tags_helper.rb
module Admins::TagsHelper
end

app/views/admins/tags/edit.html.erb
<div class="container">
	<div class="admin-tag-list">
		<h1>タグ編集</h1>

		<%= form_for @tag, url: admins_tag_path, method: :patch do |f| %>
			<%= f.label :タグ名 %>
			<%= f.text_field :tag_name %>

			<%= f.submit "変更を保存する", class:"btn btn-success" %>

			<%= link_to "削除する", admins_tag_path(@tag.id), method: :delete, data: { confirm: '本当に削除しますか？' }, class:"btn btn-danger"%>

		<% end %>
	</div>
</div>

app/views/admins/tags/index.html.erb
<div class="container">
	<div class="admin-tag-list">
		<h1>タグ一覧</h1>

		<div class="admin-tag-form">
			<%= form_for @tag, url: admins_tags_path, method: :post do |f| %>
				<%= f.label :新規タグ %>
				<%= f.text_field :tag_name %>

				<%= f.submit "追加" %>
			<% end %>
		</div>

		<table class="table table-dark">
			<hhead>
				<th>タグ名</th>
				<th>作成日</th>
				<th>更新日</th>
			</hhead>
			<% @tags.each do |tag| %>
				<tr>
					<td><%= tag.tag_name %></td>
					<td><%= l tag.created_at %></td>
					<td><%= l tag.updated_at %></td>
					<td><%= link_to "編集", edit_admins_tag_path(tag.id), class:"btn btn-success" %></td>
				</tr>
			<% end %>
		</table>
	</div>
</div>