config/routes.rb
Rails.application.routes.draw do
	devise_for :users

	devise_for :admins, controllers: {
		sessions: "admins/sessions",
		passwords: "admins/passwords"
	}

	root to: "homes#top"
	get "home/about", to: "homes#about"
	get "search", to: "homes#search"

	resources :users, except:[:new, :create]

	resources :posts, except:[:edit, :update] do
		resources :post_comments, only:[:create, :destroy]
		resources :likes, only:[:create, :destroy]
	end

	resources :notifications, only:[:index]
	delete "notifications/destroy", to: "notifications#destroy_all"

    namespace :admins do
		get "top", to: "users#top"

    	resources :users, only:[:index, :edit, :update]

    	resources :tags
    end
end

app/models/post.rb
class Post < ApplicationRecord
	mount_uploader :image, ImageUploader
	mount_uploader :video, VideoUploader

	belongs_to :user
	has_many :post_comments
	has_many :likes, dependent: :destroy
	belongs_to :tag
	has_many :notifications, dependent: :destroy

	with_options presence: true do
	  validates :title, length: { in: 1..30 }
	  validates :body, length: { in: 1..140 }
	  validates :image
	end

	def liked_by?(user)
    likes.where(user_id: user.id).exists?
	end

	def create_notification_by(current_user)
    notification = current_user.active_notifications.new(
      post_id: id,
      visited_id: user_id,
      action: "like"
    )
    notification.save if notification.valid?
  end

  def create_notification_comment!(current_user, post_comment_id)
    temp_ids = PostComment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct

    temp_ids.each do |temp_id|
        save_notification_comment!(current_user, post_comment_id, temp_id['user_id'])
    end

    save_notification_comment!(current_user, post_comment_id, user_id) if temp_ids.blank?
	end

  def save_notification_comment!(current_user, post_comment_id, visited_id)
    notification = current_user.active_notifications.new(
			post_id: id,
			post_comment_id: post_comment_id,
			visited_id: visited_id,
			action: 'comment'
    )

    if notification.visiter_id == notification.visited_id
    	notification.checked = true
    end

    notification.save if notification.valid?
   end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, only:[:new, :create, :show, :destroy]
	before_action :get_post, only:[:show, :destroy]

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id

		if @post.save
			redirect_to posts_path
		else
			render "posts/new"
		end
	end

	def show
		@post_comment = PostComment.new
		@post_comments = PostComment.where(post_id: @post.id)
	end

	def index
		@posts = Post.page(params[:page]).reverse_order
	end

	def destroy
		@post.destroy
		redirect_to user_path(@post.user.id)
	end

	private

	def get_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(
			:title,
			:body,
			:image,
			:video,
			:tag_id
		)
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post_form.html.erb
<div class="post-new-form">
	<h2>投稿画面</h2>

	<%= form_for @post do |f| %>
		<div class="post-error-messages">
			<%= render 'layouts/error_messages', obj: @post %>
		</div>

		<div class="row">
			<div class="col-xs-3">

				<div>
					<%= f.label :タイトル %><br>
					<%= f.text_field :title, placeholder: "タイトルを記入" %>
				</div>

				<div>
					<%= f.label :タグ %><br>
					<td><%= f.collection_select :tag_id, Tag.all, :id, :tag_name, include_blank: "--タグを選択してください--" %></td>
				</div>

				<div>
					<%= f.label :内容 %><br>
					<%= f.text_area :body, placeholder: "見どころを記入！", class:"post-new-body" %>
				</div>

				<div><%= f.submit "投稿する", class:"btn btn-primary" %></div>
				<div><%= link_to "topに戻る", root_path, class:"btn btn-info" %></div>
			</div>


			<div class="col-xs-9">

				<div class="post-new-img">
					<%= f.label :画像 %>
					<%= f.file_field :image, id: :post_img %>
					<div><%= image_tag "no_image.jpg", id: :post_img_prev %></div>
				</div>

				<div class="post-new-video">
					<%= f.label :動画 %>
					<%= f.file_field :video, id: :post_video %>
					<div><%= video_tag "no_image.jpg", controls: true, id: :post_video_prev %></div>
				</div>

			</div>
		</div>
	<% end %>

</div>

app/views/posts/_post_index.html.erb
<% posts.each do |post| %>
	<div class="row post-list">
		<div><% if post.user.profile_image? %>
				<%= image_tag post.user.profile_image.url, class:"user_profile_image_post_index" %>
			<% else %>
					<i class="fas fa-user-circle fa-5x"></i>
			<% end %>
			<br>
			<%= link_to post.user.nickname, user_path(post.user.id), class:"user-link" %>
		</div>

		<div><%= link_to post.title, post_path(post.id), class:"post_title" %><br>
			<i class="fas fa-tag"></i> <%= post.tag.tag_name %><br>
			<i class="fas fa-calendar-alt fa-lg"></i> <%= l post.created_at %>
		</div>

		<div><%= link_to post_path(post.id) do %>
				<%= image_tag post.image.url, class:"post-index-image"%>
			<% end %>
		</div>

		<div>
			<% if user_signed_in? %>
				<% if post.liked_by?(current_user) %>
					<i class="fa fa-heart fa-lg" aria-hidden= "true" style="color: red;"></i>
						<%= post.likes.count %>
				<% else %>
					<i class="fa fa-heart fa-lg" aria-hidden= "true"></i>
						<%= post.likes.count %>
				<% end %>
			<% else %>
					<i class="fa fa-heart fa-lg" aria-hidden= "true"></i>
						<%= post.likes.count %>
			<% end %>
			<br>
			<i class="far fa-comment-dots fa-lg"></i> <%= post.post_comments.count %>
		</div>
	</div>
<% end %>
<%= paginate posts %>

app/views/posts/index.html.erb
<div class="row post-view">
	<div class="col-xs-3 user-profile">
		<% if user_signed_in? %>
			<%= render "users/profile", user: current_user %>
		<% end %>
	</div>

	<div class="col-xs-6">
		<%= render "posts/post_index", posts: @posts %>
	</div>
</div>

app/views/posts/new.html.erb
<div class="post-view">
	<%= render "posts/post_form", post: @post %>
</div>

app/views/posts/show.html.erb
<div class="row post-view-show">

	<div class="col-xs-3 user-profile">
		<% if user_signed_in? %>
			<%= render "users/profile", user: @post.user %>
		<% end %>
	</div>

	<div class="col-xs-9 post-show-all">
		<div class="post-show-title"><span><%= @post.title %></span></div>
		<div class="post-show-tag">
			<span>
				<i class="fas fa-tag"></i> <%= @post.tag.tag_name%>
			</span>
		</div>

		<div class="post-show-like">
			<span><i class="fas fa-calendar-alt"></i> <%= l @post.created_at%></span><br>
			<span><% if @post.liked_by?(current_user) %>
					<%= link_to post_like_path(@post), method: :delete do %>
						<i class="fa fa-heart" aria-hidden= "true" style="color: red;"></i>
					<% end %>
						<%= @post.likes.count %>
				  <% else %>
						<%= link_to post_likes_path(@post), method: :post do %>
							<i class="fa fa-heart" aria-hidden= "true"></i>
						<% end %>
						<%= @post.likes.count %>
				  <% end %>
			</span>
			<span><i class="far fa-comment-dots"></i> <%= @post.post_comments.count %></span>
		</div>

		<div>
			<%= image_tag @post.image.url, class:"post-image-video" %>
		</div>

		<% if @post.video? %>
			<div>
				<%= video_tag @post.video, controls: true, class:"post-image-video" %>
			</div>
		<% end %>

		<div class="post-show-body">
			<P class="post-show-body-headline">【投稿者コメント】</P>
			<p class="post-show-content"><%= simple_format(@post.body) %></p>
		</div>

		<div class="post-show-botton">
			<%= link_to "投稿一覧に戻る", posts_path, class:"btn btn-info"%>
			<% if @post.user == current_user %>
				<%= link_to "この投稿を削除する", post_path(@post.id), method: :delete, data: { confirm: '本当に、この投稿を削除しますか？' }, class:"btn btn-danger post-danger-botton"%>
			<% end %>
		</div>


		<div class="comment-area">
			<%= form_for [@post, @post_comment] do |f| %>
				<%= f.text_area :comment, placeholder: "コメントをここに記入!", class:"commment-form" %>
				<%= f.submit "コメントする" %>
			<% end %>
		</div>

			<% @post.post_comments.sort.reverse.each do |post_comment| %>
				<div class="post-show-comments">
					<div class="post-comment-user">
						<% if post_comment.user.profile_image? %>
							<%= image_tag post_comment.user.profile_image.url, class:"post-comment-user-profileimage"%>
						<% else %>
							<i class="fas fa-user-circle fa-3x"></i>
						<% end %>
						<%= post_comment.user.nickname %>
						<span class="post-comment-user-date">
							<%= l post_comment.created_at %>
						</span>
					</div>
					<div><%= simple_format(post_comment.comment) %>
						<% if post_comment.user == current_user %>
							<%= link_to "削除", post_post_comment_path(@post, post_comment), method: :delete, data: { confirm: '本当に削除しますか？' }, class:"btn btn-danger btn-destroy"%>
						<% end %>
					</div>
				</div>
			<% end %>
	</div>

</div>