config/routes.rb
Rails.application.routes.draw do
	devise_for :users

	devise_for :admins, controllers: {
		sessions: "admins/sessions",
		passwords: "admins/passwords"
	}

	root to: "homes#top"
	get "home/about", to: "homes#about"
	get "search", to: "homes#search"

	resources :users, except:[:new, :create]

	resources :posts, except:[:edit, :update] do
		resources :post_comments, only:[:create, :destroy]
		resources :likes, only:[:create, :destroy]
	end

	resources :notifications, only:[:index]
	delete "notifications/destroy", to: "notifications#destroy_all"

    namespace :admins do
		get "top", to: "users#top"

    	resources :users, only:[:index, :edit, :update]

    	resources :tags
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/notification.rb
class Notification < ApplicationRecord
	default_scope->{order(created_at: :desc)}

	belongs_to :post, optional: true
	belongs_to :post_comment, optional: true
	belongs_to :visiter, class_name: 'User',
					foreign_key: 'visiter_id', optional: true
	belongs_to :visited, class_name: 'User',
					foreign_key: 'visited_id', optional: true

end

app/models/post.rb
class Post < ApplicationRecord
	mount_uploader :image, ImageUploader
	mount_uploader :video, VideoUploader

	belongs_to :user
	has_many :post_comments
	has_many :likes, dependent: :destroy
	belongs_to :tag
	has_many :notifications, dependent: :destroy

	with_options presence: true do
	  validates :title, length: { in: 1..30 }
	  validates :body, length: { in: 1..140 }
	  validates :image
	end

	def liked_by?(user)
    likes.where(user_id: user.id).exists?
	end

	def create_notification_by(current_user)
    notification = current_user.active_notifications.new(
      post_id: id,
      visited_id: user_id,
      action: "like"
    )
    notification.save if notification.valid?
  end

  def create_notification_comment!(current_user, post_comment_id)
    temp_ids = PostComment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct

    temp_ids.each do |temp_id|
        save_notification_comment!(current_user, post_comment_id, temp_id['user_id'])
    end

    save_notification_comment!(current_user, post_comment_id, user_id) if temp_ids.blank?
	end

  def save_notification_comment!(current_user, post_comment_id, visited_id)
    notification = current_user.active_notifications.new(
			post_id: id,
			post_comment_id: post_comment_id,
			visited_id: visited_id,
			action: 'comment'
    )

    if notification.visiter_id == notification.visited_id
    	notification.checked = true
    end

    notification.save if notification.valid?
   end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user
	belongs_to :post

	validates :comment, presence: true, length: { in: 1..140 }
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :posts

	validates :tag_name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :validatable

	mount_uploader :profile_image, ProfileImageUploader

	has_many :posts, dependent: :destroy
	has_many :post_comments, dependent: :destroy
	has_many :likes, dependent: :destroy
	has_many :active_notifications, class_name: "Notification",
				foreign_key: "visiter_id", dependent: :destroy
	has_many :passive_notifications, class_name: "Notification",
				foreign_key: "visited_id", dependent: :destroy

	enum is_active: {Available: true, Invalid: false}

	with_options presence: true do
	  validates :email
	  validates :nickname, length: { in: 1..20 }
	end

	def active_for_authentication?
		super && (self.is_active === "Available")
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	private

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys:
			[:email, :nickname]
		)
	end

	def after_sign_up_path_for(resource)
		root_path
    end

    def after_sign_in_path_for(resource)
    	root_path
    end

    def after_sign_out_path_for(resource)
    	root_path
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
		@post_rank = Post.find(
			Like.group(:post_id).order('count(post_id) desc')
			.limit(3).pluck(:post_id)
		)
		@posts = Post.all
	end

	def about
	end

	def search
		search = params[:search]

		@posts = Post.where("title LIKE? OR body LIKE?", "%#{search}%", "%#{search}%" )
						.page(params[:page])
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :authenticate_user!

	def create
		post = Post.find(params[:post_id])
		like = Like.new
		like.user_id = current_user.id
		like.post_id = post.id
		like.save
		post.create_notification_by(current_user)
		redirect_to request.referrer
	end

	def destroy
		post = Post.find(params[:post_id])
		like = current_user.likes.find_by(post_id: post.id)
		like.destroy
		redirect_to request.referrer
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, only:[:new, :create, :show, :destroy]
	before_action :get_post, only:[:show, :destroy]

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id

		if @post.save
			redirect_to posts_path
		else
			render "posts/new"
		end
	end

	def show
		@post_comment = PostComment.new
		@post_comments = PostComment.where(post_id: @post.id)
	end

	def index
		@posts = Post.page(params[:page]).reverse_order
	end

	def destroy
		@post.destroy
		redirect_to user_path(@post.user.id)
	end

	private

	def get_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(
			:title,
			:body,
			:image,
			:video,
			:tag_id
		)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :get_user, only:[:show, :edit, :update, :destroy]

	def show
		@posts = Post.where(user_id: @user.id).reverse_order.page(params[:page])
	end

	def index
		@users = User.where(is_active: true).page(params[:page]).per(12)
	end

	def edit
	end

	def update
		if	@user.update(user_params)
			redirect_to user_path(current_user)
		else
			render ("users/edit")
		end
	end

	def destroy
		@user.destroy
		redirect_to root_path
	end

	private

	def get_user
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(
			:nickname,
			:profile_image,
			:email,
			:is_active
		)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
	def notification_form(notification)
		@visiter = notification.visiter
		@post_comment = nil
		@visiter_comment = notification.post_comment_id

		case notification.action
			when "like" then
				tag.a(notification.visiter.nickname, href:user_path(@visiter)) + "が" +
					tag.a("あなたの投稿", href:post_path(notification.post_id))+"にいいねしました"

			when "comment" then
			    @post_comment = PostComment.find_by(id: @visiter_comment)
			    @post_comment_comment = @post_comment.comment
			    tag.a(notification.visiter.nickname, href:user_path(@visiter)) + "が" +
			    	tag.a("あなたの投稿", href:post_path(notification.post_id))+"にコメントしました"
		end

    end

    def unchecked_notifications
    	if user_signed_in?
    		@notifications = current_user.passive_notifications.where(checked: false)
    							.where.not(visiter_id: current_user.id)
    	end
	end
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger error_message">
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<p class="top-logo"><%= link_to "Your best Games", root_path, class:"top-logo-text" %></p>

<% if user_signed_in? %>
  <span class="login-user">ようこそ<%= current_user.nickname %>さん！</span>
<% end %>

<div class="search_tag">
    <%= form_tag(search_path, method: :get) do %>
      <%= text_field_tag :search, "", placeholder: "投稿を検索"%>
      <%= submit_tag "検索" %>
    <% end %>
</div>

<div id="sp-menu">
  <h1>MENU</h1>

  <% if user_signed_in? %>
    <ul>
      <li><i class="fas fa-user fa-3x"></i> <%= link_to "プロフィール", user_path(current_user) %></li>
      <li><i class="fas fa-photo-video fa-3x"></i> <%= link_to "投稿リスト", posts_path %></li>
      <li><i class="fas fa-users fa-3x"></i> <%= link_to "ユーザリスト", users_path %></li>
      <li><i class="fas fa-sign-out-alt fa-3x"></i> <%= link_to "LogOut", destroy_user_session_path, method: :delete %></li>
    </ul>
  <% else %>
    <ul>
      <li><i class="fas fa-gamepad fa-3x"></i> <%= link_to "About", home_about_path %></li>
      <li><i class="fas fa-photo-video fa-3x"></i> <%= link_to "投稿一覧", posts_path %></li>
      <li><i class="fas fa-user-plus fa-3x"></i> <%= link_to "SignUp", new_user_registration_path %></li>
      <li><i class="fas fa-sign-in-alt fa-3x"></i> <%= link_to "LogIn", new_user_session_path %></li>
    </ul>
  <% end %>
</div>

<div id="list-icon">
  <span class="notification-circle">
    <% if user_signed_in? %>
      <% if unchecked_notifications.any? %>
           <i class="fa fa-circle" style="color: gold;"></i>
      <% end %>
    <% end %>
  </span>

  <%= link_to notifications_path do %>
    <i class="fas fa-bell fa-3x"></i>
  <% end %>

  <%= link_to new_post_path do %>
    <i class="fas fa-plus-circle fa-3x"></i>
  <% end %>

  <a class="menu-trigger" href="#">
    <span></span>
    <span></span>
    <span></span>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YourBestGames</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/fd999642e4.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrap">

      <header>
        <%= render "layouts/header" %>
      </header>

      <%= yield %>

      <footer>
        <div class="footer">
          <% if admin_signed_in? %>
            <P><%= link_to "Your best Games", admins_top_path, class:"footer-text" %></P>
          <% else %>
            <P><%= link_to "Your best Games", new_admin_session_path, class:"footer-text" %></P>
          <% end %>
        </div>
      </footer>

    </div>
  </body>
</html>